### ISSUE TITLE
Default RHEL `jail.conf` includes nonexistent `paths-fedora.conf` file

### ISSUE THREAD

**Issue by jearls** [lelutin/puppet-fail2ban#12]
The default RHEL `jail.conf` template (`rhel_jail.conf.erb`) tries to include the `paths-fedora.conf` file:
    [INCLUDES]
    before = paths-fedora.conf

However, in fail2ban before `0.9`, the `[INCLUDES]` section is not supported in `jail.conf`.  This causes the service not to start:

```
# cat /etc/redhat-release
CentOS release 5.5 (Final)
# rpm -q fail2ban
fail2ban-0.8.14-1.el5
# service fail2ban start
Starting fail2ban: WARNING 'enabled' not defined in 'INCLUDES'. Using default one: 'false'
WARNING 'logpath' not defined in 'INCLUDES'. Using default one: '/var/log/messages'
ERROR  Found no accessible config files for 'filter.d/INCLUDES' under /etc/fail2ban
ERROR  Unable to read the filter
ERROR  Errors in jail 'INCLUDES'. Skipping...
                                                           [FAILED]
#
```

**Comment by jearls** [comment]
Never mind.  I just noticed the "redhat >= 6" although in reality the restriction is not on the redhat version but on the version of fail2ban (epel hosts 0.8.14 with el5, 0.9.3 with el6)

**Comment by lelutin** [comment]
Hi there, sorry for my lack of response I've been unable to followup on most stuff lately :\

the "restriction" you're talking about, I believe is the versions noted down in the metadata.json file (thus showing up as supported versions on the forge). It doesn't mean we should be restricting support.

From what I see here[0] version 5 of CentOS is still supported until 2017, so it might be interesting to add support for this version of the distro if the necessary changes are worth the 1 year support that's left for the OS (e.g. I would suggest to remove support for centos 5 after it has gone EOL).

[0]: https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule

I'd be open to finding out, with your help, what details make the module or the service not able to run properly on centos 5.

If we only need to create a new default template for jail.conf and maybe some alternative path strings for the default jails, then it doesn't sound too difficult :)

**Comment by lelutin** [comment]
so first details first. are you able to get the default jail.conf file from jail2ban on centos 5 and pastebin it (or gist)? from there we can figure out how to build the template for jail.conf and what proper path strings to use for example jails

**Comment by jearls** [comment]
Here is the jail.conf from `0.8.14-1.el5`: https://gist.github.com/jearls/cafdaaae19976db9e3a0644a0760e9cb

**Comment by jearls** [comment]
fail2ban version 0.8.x does not support includes, and doesn't have the pre-defined path variables.

Given that all of your service-specific jail subclasses (`fail2ban::jail::ssh` for example) use those pre-defined path variables for the RedHat family, either you need to update all those jail subclasses to *not* use the pre-defined path variables, or you need to create a concat template for pre-0.9.x that defines them.

The problem is you can't really tell what version of fail2ban will be installed, so I guess you would have to make the assumption that el5 always installs 0.8.x and newer than el5 always installs 0.9.x or newer.

**Comment by lelutin** [comment]
I usually base the assumptions about software version on the version that's available through the official package repositories. that assumption might be wrong for some distros. for redhat-based distros I expect ppl to use elX where X is the same version number as the distro version in use. I'm not sure however if that could be wrong.

for the config file, we could reuse the debian template for rhel/centos 5 since it does not have an includes section.

then we'd have to special-case all jails that use rhel-specific path variables so that rhel/centos 5 don't use them.

**Comment by jearls** [comment]
another solution might be too have a top level parameter that indicates version 0.8 or 0.9.  i just hit a use case at work where it's being insisted upon that we continue to use 0.8 in el6 because that's what we already have security approval for. :p

**Comment by jearls** [comment]
i can't comment on the use of the Debian files since i don't have easy access to the module at this point (responding from my phone)

**Comment by lelutin** [comment]
RHEL 5 has gone to EOL, I wasn't fast enough to solve this :\

I'll close this issue since I'm now not considering supporting RHEL 5 anymore.
