### ISSUE TITLE
Create Puppet Strings documentation

### ISSUE THREAD

**Issue by jcharaoui** [lelutin/puppet-fail2ban#37]

**Comment by lelutin** [comment]
@jcharaoui I've sent a commit that prepares puppet-strings generation : ddbd77e . it adds a rake task to compile documentation with puppet-strings.

I haven't figured out how to make travis generate this automatically yet.

so I guess we can start documenting!

**Comment by jcharaoui** [comment]
I'm not sure either, I'm not familiar at all with Travis. If teh module moves (or is gets mirrored) on GitLab then it should be easy to copy the exmaple from the other modules.

**Comment by lelutin** [comment]
@jcharaoui yep sure :)

in all circumstances I think our next move should be to add the docstrings.

I've run puppet strings generate locally and it didn't find out the custom types in types/*.pp .. do you know if that's a bug of some sort with puppet-strings? or maybe just an unimplemented feature

**Comment by lelutin** [comment]
I've pushed docstrings for puppet strings in 33d51c5

puppet-strings doesn't seem to know what to do with custom types with the puppet 4.x syntax. this is really unfortunate :(

We'll have to auto-generate the documentation files but that can wait until we decide where to do that. for now we do have puppet-strings documentation so I'll close this issue.

... and with that we're ready for 3.0.0 release! (finally)
