### ISSUE TITLE
Support Debian 10 (buster) / Ubuntu 18.04 (bionic)

### ISSUE THREAD

**Issue by OrangeDog** [lelutin/puppet-fail2ban#38]
I don't know whether any changes would be required other than to the manifest.
The fail2ban version is 0.10.2

**Comment by lelutin** [comment]
Hi there!

The repository was rearranged to form the new 3.x versions on the master, and keep the old code around some time as the 2.x branch.

The new code on the master branch supports puppet 4.x and 5.x while the old code on the 2.x branch supports puppet 2.7 and 3.x

Normally there's no release number restrictions in the code on the master branch. The only place that restricts what can run the code is in config.pp: https://github.com/lelutin/puppet-fail2ban/blob/master/manifests/config.pp#L74

So, I believe that debian buster and ubuntu 18.04 should be able to run the current code on master. Can you try running the module on these and report if you encounter any problems doing so?

**Comment by gfa** [comment]
I use the release 3.1.0 on buster hosts without problems so far, also on stretch hosts with backported fail2ban (0.10.2-2~bpo9+1 ATM)

**Comment by lelutin** [comment]
@gfa thanks for this info! I will bump version support in metadata.json soon (hopefully this week-end) to indicate that it should "just work".
