### ISSUE TITLE
Build 'amazon-ebs' errored: Error uploading modules: lstat /vagrant: no such file or directory

### ISSUE THREAD

**Issue by nbrys** [lelutin/puppet-fail2ban#45]
When using packer to build an AWS AMI, we encountered the following error:

`    amazon-ebs: Uploading local modules from: puppet/modules
    amazon-ebs: Creating directory: /tmp/packer-puppet-masterless/module-0
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-04c4a1e244b65a1fe)...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error uploading modules: lstat /vagrant: no such file or directory`

In this module/test/modules/fail2ban points to /vagrant/ which is invalid

**Comment by nbrys** [comment]
Created PR for this: https://github.com/lelutin/puppet-fail2ban/pull/46

**Comment by lelutin** [comment]
I've merged #46 so I guess we can close this as well.
