### ISSUE TITLE
fail2ban::jail is missing many parameters

### ISSUE THREAD

**Issue by lelutin** [lelutin/puppet-fail2ban#47]
accoring to documentation, there are many parameters to a jail definition that this module is not exposing.

https://manpages.debian.org/testing/fail2ban/jail.conf.5.en.html#JAIL_CONFIGURATION_FILE(S)_(jail.conf)

The missing parameters should be added as params to `fail2ban::jail`

**Comment by hubide** [comment]
There's a nice feature for bantime increment that's been available for a while in the debian version.
https://visei.com/2020/05/incremental-banning-with-fail2ban/

I might add this feature if I find the time

**Comment by lelutin** [comment]
huh wait... that's a thing? why did I miss those previously :( ...sometimes finding fail2ban's documentation is actually pretty hard. those values are still not documented in the manpage in debian sid.

good find though! from what I can see Vox Pupuli has not implemented this yet in their similar module https://github.com/voxpupuli/puppet-fail2ban

I'm interested in reviewing and merging your changes if you happen to implement this :)

I guess now the big question is "what name should we give those new parameters?" `$bantime` is already taken and AFAIR puppet doesn't permit dots in variable names. so.... mabye we permit `$bantime` to be either a string of the current format, or a hash with certain expected keys (e.g. with a type alias we can restrict which keys should be found)?

I wonder where the current value for `$bantime` would live in the hash-form of the variable. a key that's an empty string? (i.e. ` bantime => { "" => "1d" }` -- meh) a repeat of `bantime` for the key name? (i.e. `bantime => { "bantime" => "1d" }` -- slightly more meh)

**Comment by lelutin** [comment]
also fyi, on the `main` branch I've "recently" implemented more parameters for a couple of the different resources -- although none of the `bantime.*` ones. I haven't released this new work yet on forge since I hit a snag when enabling puppet-lint in CI. but that won't be a blocker to your addition if you send something this way

**Comment by hubide** [comment]
well, until we can use v.4+ in our aging puppet setup, I don't think I'll be able to jump in here :/
In the mean time, I've used this on each jail I want to implement the increment feature
` 'additional_options' => {
    'bantime.increment' => 'true',
}, `

This option can also be specified in local.conf/fail.conf

As for the name, maybe split existing bantime var and new features. New parameters could be a hash named 'bantime-extra' or something.

**Comment by lelutin** [comment]
so what I found for the more general context that lists options is: https://github.com/fail2ban/fail2ban/blob/54c0effceb998b73545073ac59c479d9d9bf19a4/fail2ban/server/transmitter.py#L156-L411
The `bantime.*` options are found under a Jail method: https://github.com/fail2ban/fail2ban/blob/54c0effceb998b73545073ac59c479d9d9bf19a4/fail2ban/server/jail.py#L225-L268

on the client side there's also this which is maybe easier to read: https://github.com/fail2ban/fail2ban/blob/54c0effceb998b73545073ac59c479d9d9bf19a4/fail2ban/server/transmitter.py#L156-L411


I'll start building a list of options in the description so that I (we?) can start checking them out if we know they're implemented in the module.

**Comment by lelutin** [comment]
err ... right. this is not gitlab :P  apparently there's no description that can be modified.

so here's the list:

Logging:

- [ ] loglevel
- [ ] logtarget
- [ ] syslogsocket
- [ ] allowipv6

Thread:

- [ ] thread

Database:

- [ ] dbfile
- [ ] dbmaxmatches
- [ ] dbpurgeage

Jail:

- [ ] idle

Filter:

- [ ] ignoreself
- [ ] addignoreip
- [ ] delignoreip
- [ ] ignorecommand
- [ ] ignorecache
- [ ] addlogpath
- [ ] dellogpath
- [ ] logencoding
- [ ] addjournalmatch
- [ ] deljournalmatch
- [ ] prefregex
- [ ] addfailregex
- [ ] delfailregex
- [ ] addignoreregex
- [ ] delignoreregex
- [ ] usedns
- [ ] findtime
- [ ] datepattern
- [ ] logtimezone
- [ ] maxmatches
- [ ] maxretry
- [ ] maxlines

command:

- [ ] bantime
- [ ] attempt
- [ ] bantime.increment
- [ ] bantime.maxtime
- [ ] bantime.rndtime
- [ ] bantime.formula
- [ ] bantime.factor
- [ ] bantime.maxtime
- [ ] bantime.multipliers
- [ ] banip
- [ ] unbanip
- [ ] addaction
- [ ] delaction
- [ ] action

**Comment by lelutin** [comment]
so I missed two options for filters. both of them are not recommended to bet set at global level but wth I can add them anyway with a warning in the documentation for the option, and then all of the bantime.*

and with those eventually added I'll be able to close this issue with more certainty now.

**Comment by lelutin** [comment]
wth is this code (fail2ban).. there's apparently an additional option `bantime.overalljails` that the JailReader class knows about, but that never gets handled by the server's Jail class. it's also documented in the default jail.conf file.

...but is it actually a thing if the server doesn't handle it? I guess I'll have to run some tests somehow
